---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Ensure the default session to configure is available
  file:
    path: '/usr/share/xsessions/{{ dm_user_session }}.desktop'
    state: 'file'
  when: (dm_user_session != omit)

- import_tasks: 'gdm.yml'
  when: (dm__name == "gdm")

- import_tasks: 'lightdm.yml'
  when: (dm__name == "lightdm")

- name: Ensure specified packages are in there desired state
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ dm__packages }}'
    - '{{ dm__package_map[dm__name] }}'
    - '{{ dm__lightdm_packages if (dm__name == "lightdm") else [] }}'
    - '{{ dm__gdm_packages if (dm__name == "gdm") else [] }}'
  tags: [ 'role::dm:pkg' ]

- name: Ensure alternative display managers are absent
  package:
    name: '{{ item }}'
    state: 'absent'
  with_flattened: '{% set list = [] %}{% for name in dm__package_map | reject("equalto", dm__name) | list %}{% set _ = list.append(dm__package_map[name]) %}{% endfor %}{{ list }}'
  tags: [ 'role::dm:pkg' ]

- name: Configure default display manager in debconf
  debconf:
    name: 'shared'
    question: 'shared/default-x-display-manager'
    vtype: 'select'
    value: '{{ dm__name }}'

- name: Configure default display manager in X11
  template:
    src: 'etc/X11/default-display-manager.j2'
    dest: '/etc/X11/default-display-manager'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure default display manager in systemd
  file:
    src: '/lib/systemd/system/{{ dm__package_map[dm__name] }}.service'
    dest: '/etc/systemd/system/display-manager.service'
    state: 'link'
  when: (ansible_distribution|d("") == "Debian")

- name: Configure default session manager
  alternatives:
    name: 'x-session-manager'
    path: '{{ dm__session_manager }}'
  when: dm__session_manager != omit
