---

- name: Restart gdm
  service:
    name: 'gdm3'
    state: 'restarted'
  when: dm__restart_on_configuration_change | bool

- name: Restart lightdm
  service:
    name: 'lightdm'
    state: 'restarted'
  when: dm__restart_on_configuration_change | bool
